name: Build and Deploy WAR to Docker Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Must be your local Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build WAR
        run: mvn clean package

      - name: Prepare WAR for deployment
        run: |
          mkdir output
          cp target/*SNAPSHOT.war output/TemperatureApp.war

      - name: Deploy WAR to Docker Tomcat
        run: |
          docker cp output/TemperatureApp.war tomcat_server:/usr/local/tomcat/webapps/TemperatureApp.war
          docker restart tomcat_server


      - name: Deploy WAR to Docker Tomcat
        run: |
          docker cp output/TemperatureApp.war tomcat_server:/usr/local/tomcat/webapps/TemperatureApp.war
          docker restart tomcat_server
